site_name: CUSTOMER SUPPORT SYSTEM (cSupport) <br> USER DOCUMENTATION
theme:
  name: readthedocs

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
nav:
 - Overview: 
   - Introduction: index.md
 - Getting Started:
   - Login: getting_started.md
 - Home: 
   - User Dashboard: user-dashboard.md
   - Navigation Bar: navigation-bar.md
   - Ticket Details: ticket-details.md
 - Customer Search Dashboard:
    - Customer View: customer-view.md
    - Customer Details: customer-details.md
copyright: |
  Documented By Prajin Shrestha.<br>
  &copy; 2024 Worldlink Communications <a href="mailto:programming@worldlink.com.np">Programming</a>.
  